# Reload tmux configuration quickly using [prefix] + r key
bind-key r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

# Extend message display time
set-option -g display-time 300

# Use vim key bindings
setw -g mode-keys vi

unbind -T copy-mode-vi MouseDragEnd1Pane
bind -T copy-mode-vi y send-keys -X copy-pipe
bind -T copymode-vi MouseDown1Pane send-keys -X clear-selection \; select-pane


# Override default split bindings to preserve current directory
unbind '"'
bind-key '"' split-window -h -c "#{pane_current_path}"
unbind %
bind-key % split-window -v -c "#{pane_current_path}"

# Easier window split shortcut keys [prefix + v] [prefix + h]
bind-key v split-window -h -c "#{pane_current_path}"
bind-key h split-window -v -c "#{pane_current_path}"

# Quick window selection
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

bind > swap-pane -D
bind < swap-pane -U

# Resize panes with Ctrl+Shift+h/j/k/l
bind -n C-H resize-pane -L 5
bind -n C-J resize-pane -D 5
bind -n C-K resize-pane -U 5
bind -n C-L resize-pane -R 5

# List of plugins
# REMEMBER - Use [prefix] + I to install plugins 
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'noscript/tmux-mighty-scroll'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'RyanMillerC/better-vim-tmux-resizer'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Map Ctrl + Alt + L to clear screen with vim-tmux-navigator installed
set -g @vim_navigator_prefix_mapping_clear_screen "C-M-l"

# Options to make tmux more pleasant
set -g mouse on
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set-option -g status-position top
set-window-option -g automatic-rename on
set-option -g set-titles on
bind p paste-buffer
set -g base-index 1
set-window-option -g pane-base-index 1
set -g renumber-windows on
set-window-option -g automatic-rename off
set-option -g repeat-time 0
set -sg escape-time 1
setw -g monitor-activity on
set -g visual-activity on
setw -g monitor-bell off
set -s set-clipboard external 
set -as terminal-features ',rxvt-unicode-256color:clipboard'
set-option -g focus-events on

## Restore Vim sessions
set -g @resurrect-dir "$HOME/.tmux/resurrect"
set -g @continuum-restore 'on'
# set -g @continuum-interval 900
set -g @resurrect-capture-pane 'on'
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-strategy-nvim 'session'

bind-key -n M-d command-prompt "run-shell 'tmux-resurrect delete-session %%'"

# Configure the catppuccin plugin
# IMPORTANT: Remember to install an appropriate nerd font and set it as default for terminal app
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "slanted"
set -g @catppuccin_background "#101010"

# Load catppuccin
run ~/.tmux/plugins/tmux/catppuccin.tmux

set -g status-right-length 100
set -g status-left-length 50 
set -g status-left "#{prefix_highlight}"
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"

# Restore tmux sessiones saved by resurrect
run-shell ~/.tmux/plugins/tmux-resurrect/resurrect.tmux

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

